name: CI
on:
  pull_request:
  push:
env:
  CI: true

jobs:
  test:
    name: Tests for Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ["0.12", "4", "5", "6", "8", "10", "12", "14", "16", "18"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0

      - name: Set Node.js version
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test
